CONFIG_ZMK_USB=y

# 2 peripherals + overhead for pairing/scanning
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2
CONFIG_BT_MAX_CONN=6
CONFIG_BT_MAX_PAIRED=6

# USB serial logging for debugging
CONFIG_ZMK_USB_LOGGING=y
