# Required when building with nice_nano without the //zmk qualifier
# (mirrors nice_nano_nrf52840_zmk_2_0_0_defconfig)
CONFIG_ZMK_BLE=y
CONFIG_NVS=y
CONFIG_SETTINGS_NVS=y
CONFIG_FLASH=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_FLASH_MAP=y
